- hosts: pis
  sudo: true
  tasks:

    - name: install git
      apt: name=git

    - include: ansible/network.yml

    - include: ansible/openvpn.yml

    - include: ansible/nodejs.yml

    - include: ansible/projects.yml

    - include: ansible/nginx.yml