---

    - name: install build esentials
      apt: name=build-essential

    - name: get the package script
      shell: >
        curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
        creates=/etc/apt/sources.list.d/nodesource.list

    - name: install nodejs
      apt: name=nodejs

    - name: install bower
      shell: >
        npm install -g bower
        creates=/usr/lib/node_modules/bower

    - name: install gulp
      shell: >
        npm install -g gulp
        creates=/usr/lib/node_modules/gulp