---

    - name: install build esentials
      apt: name=build-essential

    - name: nodejs deb herunterladen
      get_url: url=http://node-arm.herokuapp.com/node_archive_armhf.deb dest=/tmp/node_armhf.deb

    - name: install nodejs
      apt: deb=/tmp/node_armhf.deb